name: 'CI'

on: [push]

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: yarn install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload deb
        if: matrix.platform == 'ubuntu-20.04'
        uses: actions/upload-artifact@v4
        with:
          name: HarmonyVPKTool-deb
          path: HarmonyVPKTool/src-tauri/target/release/bundle/deb/*.deb

      - name: upload appimage
        if: matrix.platform == 'ubuntu-20.04'
        uses: actions/upload-artifact@v4
        with:
          name: HarmonyVPKTool-appimage
          path: HarmonyVPKTool/src-tauri/target/release/bundle/appimage/*.AppImage

      - name: upload exe
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: HarmonyVPKTool-exe
          path: HarmonyVPKTool/src-tauri/target/release/*.exe

      - name: upload msi
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: HarmonyVPKTool-msi
          path: HarmonyVPKTool/src-tauri/target/release/bundle/msi/*.msi

      - name: upload nsis
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: HarmonyVPKTool-nsis
          path: HarmonyVPKTool/src-tauri/target/release/bundle/nsis/*.exe
        