name: CI
on: push

jobs:
  build_win:
    runs-on: windows-2022
    steps:
    - name: Setup node
      uses: actions/setup-node@master
    - name: Checkout Harmony VPK Tool
      uses: actions/checkout@v3
      with:
        path: main
    - name: Checkout r5sdk
      uses: actions/checkout@v3
      with:
        repository: 'Mauler125/r5sdk'
        path: r5sdk
    - name: Configure Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.4.1
      with:
        arch: amd64
    - name: Compile lzham
      run: | 
        cd r5sdk
        msbuild ./r5dev/vproj/liblzham.vcxproj /p:Configuration=Release
        cd ..
    - name: Checkout TFVPKTool
      uses: actions/checkout@v3
      with:
        repository: 'barnabwhy/TFVPKTool'
        path: tfvpktool
    - name: Compile TFVPKTool
      run: |
        del tfvpktool/src/lzham/lib/liblzham_x64.lib 2>null
        move r5sdk/r5dev/vproj/lib/Release/liblzham_x64.lib tfvpktool/src/lzham/lib/liblzham_x64.lib
        cd tfvpktool
        npm install
        npm run compile:base
        mkdir dist/build/Release
        move src/build/Release/lzham.node dist/build/Release/lzham.node
        move LICENSE.md dist/LICENSE.md
    - name: Move compiled TFVPKTool to Harmony VPK Tool
      run: |
        cd ..
        move tfvpktool/dist main/tfvpktool
        cd main
    - name: NPM install
      run: npm install
    - name: Build
      run: npm run build:windows
    - uses: actions/upload-artifact@v3
      with:
        name: Harmony VPK Tool
        path: builds/Harmony VPK Tool*.exe

  # build_linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Setup node
  #     uses: actions/setup-node@master
  #   - name: Checkout Harmony VPK Tool
  #     uses: actions/checkout@v3
  #     with:
  #       path: main
  #   - name: Checkout TFVPKTool
  #     uses: actions/checkout@v3
  #     with:
  #       repository: 'barnabwhy/TFVPKTool'
  #       path: tfvpktool
  #   - name: Compile TFVPKTool
  #     run: |
  #       cd tfvpktool
  #       npm install
  #       npm run compile:base
  #       mv src/build/Release/lzham.node dist/build/Release/lzham.node
  #       mv LICENSE.md dist/LICENSE.md
  #   - name: Move compiled TFVPKTool to Harmony VPK Tool
  #     run: |
  #       cd ..
  #       mv tfvpktool/dist main/tfvpktool
  #       cd main
  #   - name: NPM install
  #     run: npm install
  #   - name: Build
  #     run: npm run build:linux
  #   - uses: actions/upload-artifact@v3
  #     with:
  #       name: Harmony VPK Tool
  #       path: builds/Harmony VPK Tool*.AppImage