name: CI
on:
- push

jobs:
  build_win:
    runs-on: windows-latest
    steps:
    - name: Setup node
      uses: actions/setup-node@master
    - name: Checkout Harmony VPK Tool
      uses: actions/checkout@v3
      - path: main
    - name: Checkout TFVPKTool
      uses: actions/checkout@v3
      - repository: 'barnabwhy/TFVPKTool'
      - path: tfvpktool
    - name: Compile TFVPKTool
      run: |
        cd tfvpktool
        npm install
        npm run compile
    - name: Move compiled TFVPKTool to Harmony VPK Tool
      run: |
        cd ..
        move "tfvpktool/dist" "main/tfvpktool"
        cd main
    - name: NPM install
      run: npm install
    - name: Build
      run: npm run build:windows
    - uses: actions/upload-artifact@v3
      with:
        name: Harmony VPK Tool
        path: builds/Harmony VPK Tool*.exe

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node
      uses: actions/setup-node@master
    - name: Checkout Harmony VPK Tool
      uses: actions/checkout@v3
      - path: main
    - name: Checkout TFVPKTool
      uses: actions/checkout@v3
      - repository: 'barnabwhy/TFVPKTool'
      - path: tfvpktool
    - name: Compile TFVPKTool
      run: |
        cd tfvpktool
        npm install
        npm run compile
    - name: Move compiled TFVPKTool to Harmony VPK Tool
      run: |
        cd ..
        move "tfvpktool/dist" "main/tfvpktool"
        cd main
    - name: NPM install
      run: npm install
    - name: Build
      run: npm run build:linux
    - uses: actions/upload-artifact@v3
      with:
        name: Harmony VPK Tool
        path: builds/Harmony VPK Tool*.AppImage